# Name of the IP block
IP_NAME := periph_subsys

# Design IP dependency in 'ip' folder
RTL_IP_DEP := 

# Design IP dependency in same folder as current ip
RTL_REPO_DEP := apb_bridge gpio_ctrl

# Verification IP dependency in 'ip' folder
VERIF_IP_DEP := 

# Verification IP dependency in same folder as current ip
VERIF_REPO_DEP := 

# RTL Top level module name
RTL_TOP_NAME := periph_subsys_top

# SystemRDL CSR Source
RDL_SRC := 

include ../flows/block.mk
