# Name of the IP block
IP_NAME := gnss_receiver

# Design IP dependency in 'ip' folder
RTL_IP_DEP := 

# Design IP dependency in same folder as current ip
RTL_REPO_DEP := mcu_subsys periph_subsys apb_bridge gpio_ctrl spi_ctrl uart_ctrl

# Verification IP dependency in 'ip' folder
VERIF_IP_DEP := 

# Verification IP dependency in same folder as current ip
VERIF_REPO_DEP := 

# RTL Top level module name
RTL_TOP_NAME := gnss_receiver_top

# SystemRDL CSR Source
RDL_SRC := 

include ../flows/block.mk
