// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package gpio_ctrl_csr_pkg;

    localparam GPIO_CTRL_CSR_DATA_WIDTH = 32;
    localparam GPIO_CTRL_CSR_MIN_ADDR_WIDTH = 4;

    typedef struct packed {
        logic [31:0] next;
    } gpio_ctrl_csr__INPUT_STATUS__IVALUE__in_t;

    typedef struct packed {
        gpio_ctrl_csr__INPUT_STATUS__IVALUE__in_t IVALUE;
    } gpio_ctrl_csr__INPUT_STATUS__in_t;

    typedef struct packed {
        gpio_ctrl_csr__INPUT_STATUS__in_t INPUT_STATUS;
    } gpio_ctrl_csr__in_t;

    typedef struct packed {
        logic [31:0] value;
    } gpio_ctrl_csr__OUTPUT_CTRL_VALUE__OVALUE__out_t;

    typedef struct packed {
        gpio_ctrl_csr__OUTPUT_CTRL_VALUE__OVALUE__out_t OVALUE;
    } gpio_ctrl_csr__OUTPUT_CTRL_VALUE__out_t;

    typedef struct packed {
        logic [31:0] value;
    } gpio_ctrl_csr__OUTPUT_CTRL_ENABLE__OENABLE__out_t;

    typedef struct packed {
        gpio_ctrl_csr__OUTPUT_CTRL_ENABLE__OENABLE__out_t OENABLE;
    } gpio_ctrl_csr__OUTPUT_CTRL_ENABLE__out_t;

    typedef struct packed {
        gpio_ctrl_csr__OUTPUT_CTRL_VALUE__out_t OUTPUT_CTRL_VALUE;
        gpio_ctrl_csr__OUTPUT_CTRL_ENABLE__out_t OUTPUT_CTRL_ENABLE;
    } gpio_ctrl_csr__out_t;
endpackage
