# Name of the IP block
IP_NAME := apb_bridge

# Design IP dependency in 'ip' folder
RTL_IP_DEP := 

# Design IP dependency in same folder as current ip
RTL_REPO_DEP := 

# Verification IP dependency in 'ip' folder
VERIF_IP_DEP := 

# Verification IP dependency in same folder as current ip
VERIF_REPO_DEP := 

# RTL Top level module name
RTL_TOP_NAME := apb_bridge_top

# SystemRDL CSR Source
RDL_SRC := 

include ../flows/block.mk
