# Name of the IP block
IP_NAME := mcu_subsys

# Design IP dependency in 'ip' folder
RTL_IP_DEP := 

# Design IP dependency in same folder as current ip
RTL_REPO_DEP := 

# Verification IP dependency in 'ip' folder
VERIF_IP_DEP := 

# Verification IP dependency in same folder as current ip
VERIF_REPO_DEP := 

# RTL Top level module name
RTL_TOP_NAME := mcu_subsys_top

include ../flows/block.mk
